#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo "Hello. Moving dotfiles into ~/"

cp  $DIR/{.bashrc,.bash_profile,.gitconfig} ~/

echo "Done. Sourcing .bashrc"

source ~/.bashrc

cp $DIR/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/
sudo ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
